### ISSUE TITLE
Destructuring error

### ISSUE THREAD

**Issue by soundstep** [6to5/6to5#412]
Hi,

I noticed I get an error with the following:

```
var temperature = [0, 37, 100];
[t + 273 for (t of temperature)]; // [273, 310, 373]
```

```
/usr/local/lib/node_modules/6to5/lib/6to5/util.js:243
    throw err;
          ^
SyntaxError: src/array-comprehension.js: Unexpected token (16:9)
  14   | // Array created with 1 loop
  15   | var temperature = [0, 37, 100];
> 16   | [t + 273 for (t of temperature)]; // [273, 310, 373]
       |         ^
  17   |
  18   | // Array created with 3 loops
  19   | var suspects = ["Miss Scarlet", "Colonel Mustard"],
    at raise (/usr/local/lib/node_modules/6to5/node_modules/acorn-6to5/acorn.js:345:15)
    at unexpected (/usr/local/lib/node_modules/6to5/node_modules/acorn-6to5/acorn.js:1823:5)
    at expect (/usr/local/lib/node_modules/6to5/node_modules/acorn-6to5/acorn.js:1811:18)
    at parseExprList (/usr/local/lib/node_modules/6to5/node_modules/acorn-6to5/acorn.js:3151:9)
    at parseExprAtom (/usr/local/lib/node_modules/6to5/node_modules/acorn-6to5/acorn.js:2704:23)
    at parseExprSubscripts (/usr/local/lib/node_modules/6to5/node_modules/acorn-6to5/acorn.js:2514:28)
    at parseMaybeUnary (/usr/local/lib/node_modules/6to5/node_modules/acorn-6to5/acorn.js:2497:16)
    at parseExprOps (/usr/local/lib/node_modules/6to5/node_modules/acorn-6to5/acorn.js:2448:24)
    at parseMaybeConditional (/usr/local/lib/node_modules/6to5/node_modules/acorn-6to5/acorn.js:2425:16)
    at parseMaybeAssign (/usr/local/lib/node_modules/6to5/node_modules/acorn-6to5/acorn.js:2408:16)
```

**Comment by sebmck** [comment]
Array comprehensions aren't postfix, the correct version is `[for (t of temperature) t + 273];`. You also need to enable experimental mode as array comprehensions are an ES7 feature, see [here](https://6to5.org/docs/usage/experimental/) for more info.

**Comment by soundstep** [comment]
Oh ok, thank you for the info.
I was surprised to have it working in FF 34, any idea why? Did they start implementing proposed featured?

**Comment by sebmck** [comment]
Yeah, previously SpiderMonkey had implemented it non-standard when it was still at it's extremely early stages. See [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Array_comprehensions) for more info.

**Comment by soundstep** [comment]
Great, thank you!
