### ISSUE TITLE
Error while compiling: unknown template object-define-properties-closure

### ISSUE THREAD

**Issue by amasad** [6to5/6to5#452]
The `object-define-properties-closure` seem to have been removed from the repo however as of v2.9.4 release `es6-property-method-assignment.js` used it. A recent commit seems to have removed the usage 9f3e1eabfdb175f61e63d31b1542b4d9090d6d94 but I don't think a release has been made since.
I think a new release might solve this.
```
/usr/local/lib/node_modules/6to5/lib/6to5/util.js:243
    throw err;
          ^
ReferenceError: src/main.js: unknown template object-define-properties-closure
    at Object.exports.template (/usr/local/lib/node_modules/6to5/lib/6to5/util.js:127:24)
    at exports.ObjectExpression (/usr/local/lib/node_modules/6to5/lib/6to5/transformation/transformers/es5-property-method-assignment.js:27:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/6to5/lib/6to5/transformation/transformer.js:64:14)
    at handle (/usr/local/lib/node_modules/6to5/lib/6to5/traverse/index.js:82:33)
    at traverse (/usr/local/lib/node_modules/6to5/lib/6to5/traverse/index.js:117:7)
    at handle (/usr/local/lib/node_modules/6to5/lib/6to5/traverse/index.js:95:7)
    at traverse (/usr/local/lib/node_modules/6to5/lib/6to5/traverse/index.js:117:7)
    at handle (/usr/local/lib/node_modules/6to5/lib/6to5/traverse/index.js:95:7)
    at traverse (/usr/local/lib/node_modules/6to5/lib/6to5/traverse/index.js:105:9)
    at handle (/usr/local/lib/node_modules/6to5/lib/6to5/traverse/index.js:95:7)
```

**Comment by sebmck** [comment]
Pushed out a new release (2.10.0) that should fix this. Also includes heavy optimisations.
