### ISSUE TITLE
Error thrown from `ast-types` library

### ISSUE THREAD

**Issue by unindented** [6to5/6to5#475]
With the latest version of 6to5, all files I try to transform throw this error:

```
.../node_modules/6to5/bin/6to5/util.js:31
      throw e;
            ^
AssertionError: src/app.js: false == true
    at Visitor.PVp.visitWithoutReset (.../node_modules/6to5/node_modules/ast-types/lib/path-visitor.js:135:12)
    at Visitor.PVp.visit (.../node_modules/6to5/node_modules/ast-types/lib/path-visitor.js:117:21)
    at Function.transform (.../node_modules/6to5/node_modules/regenerator/lib/visit.js:31:18)
    at Object.exports.ast.before (.../node_modules/6to5/lib/6to5/transformation/transformers/es6-generators.js:5:17)
    at Transformer.astRun (.../node_modules/6to5/lib/6to5/transformation/transformer.js:52:25)
    at Transformer.transform (.../node_modules/6to5/lib/6to5/transformation/transformer.js:72:8)
    at .../node_modules/6to5/lib/6to5/file.js:260:17
    at Function.forEach (.../node_modules/lodash/dist/lodash.js:3297:15)
    at File.transform (.../node_modules/6to5/lib/6to5/file.js:259:5)
    at .../node_modules/6to5/lib/6to5/file.js:239:10
```

It seems to have to do with this change in the `ast-types` library: https://github.com/benjamn/ast-types/commit/e866485d72538ff9beee30fd0f1b542a1f242c8e

/cc @sebmck

**Comment by sebmck** [comment]
Looks like a bad regenerator release, I've reported it at facebook/regenerator#164. I've been having issues lately with dependencies breaking on minor versions, I'll have to make them static instead of tildes.

**Comment by unindented** [comment]
:+1:

**Comment by sebmck** [comment]
Pushed out a new release (2.11.4) that has static versions that should fix this.

**Comment by anthonator** [comment]
What version of browserify are you using?
