### ISSUE TITLE
`Import` bug via require hook

### ISSUE THREAD

**Issue by denysonique** [6to5/6to5#491]
main_file.js:
```javascript
require('6to5/register');
require('./file_to_import.es6');
```

file_to_import.es6:
```javascript
import * as request from 'request';
request.defaults({followAllRedirects: true}); // TypeError: Object [object Object] has no method 'defaults'
```

setup:
```
$ npm install 6to5 request
```
running:
```
$ node main_file.js
```

error:
```
TypeError: Object [object Object] has no method 'defaults'
    at Object.<anonymous> (/tmp/testcase/file_to_import.es6:2:9)
    at Module._compile (module.js:456:26)
    at Object.loader (/tmp/testcase/node_modules/6to5/lib/6to5/register.js:110:5)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/tmp/testcase/main_file.js:2:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```
Under 6to5-node directly code runs perfectly as well as if classic ```var request = require('request');``` is used

**Comment by AluisioASG** [comment]
Actually, you want `ìmport request from 'request';`.

**Comment by sebmck** [comment]
This is expected behaviour. As @AluisioASG said, use `import request from "request";`. See #224 for more info.
