### ISSUE TITLE
"Error: Cannot find module" when using `6to5-node -p`

### ISSUE THREAD

**Issue by timoxley** [6to5/6to5#591]
```
> 6to5-node -p "1 + 2"
Error: Cannot find module '/Users/timoxley/Projects/installed/1 + 2'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/6to5/bin/_6to5-node:76:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by timoxley** [comment]
`--help` suggests this isn't correct behaviour:

```
6to5-node --help

  Usage: 6to5-node [options] [ -e script | script.js ] [arguments]

  Options:

    -h, --help                     output usage information
    -e, --eval [script]            Evaluate script
    -p, --print                    Evaluate script and print result
    -i, --ignore [regex]           Ignore all files that match this regex when using the require hook
    -x, --extensions [extensions]  List of extensions to hook into [.es6,.js]
    -r, --experimental             Enable experimental support for proposed ES7 features
    -g, --playground               Enable playground support
    -c, --cache                    Cache compiled files and require paths
    -V, --version                  output the version number

```

Expected behaviour:

```
> node -p "1 + 2"
3
```

**Comment by timoxley** [comment]
Note `-e` is functional:

```
6to5-node -e "console.log(1 + 2)"
```

**Comment by sebmck** [comment]
```javascript
$ 6to5-node -p -e "1 + 2"
```

works. I'll add in an edgecase for passing the code to the `-p` flag.

**Comment by sebmck** [comment]
Done, thanks!
