### ISSUE TITLE
Error during installation on io.js v1.1.0 [6to5 v3.5.0]

### ISSUE THREAD

**Issue by AntouanK** [6to5/6to5#720]
Installed 3.5.0 today, and like with that last version I installed a few days ago, I get a few errors during installation.
It does complete though, and 6to5 seems to compile my files just fine...
I'm going to post a log though, might help you see what's wrong.

```bash
➜  immutabix git:(develop) ✗ sudo npm i --save-dev 6to5
npm WARN package.json immutabix@1.0.0 No description
npm WARN package.json immutabix@1.0.0 No README data

> kexec@1.0.0 install /Users/antouank/_REPOS_/immutabix/node_modules/6to5/node_modules/kexec
> node-gyp configure build

child_process: customFds option is deprecated, use stdio instead.
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/kexec/src/kexec.o
../src/kexec.cc:22:30: error: use of undeclared identifier 'F_GETFD'
    int flags = fcntl (desc, F_GETFD, 0);
                             ^
../src/kexec.cc:26:15: error: use of undeclared identifier 'FD_CLOEXEC'
    flags &= ~FD_CLOEXEC; //clear FD_CLOEXEC bit
              ^
../src/kexec.cc:27:25: error: use of undeclared identifier 'F_SETFD'
    return fcntl (desc, F_SETFD, flags);
                        ^
../src/kexec.cc:43:34: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
static Handle<Value> kexec(const Arguments& args) {
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/antouank/.node-gyp/1.1.0/deps/v8/include/v8.h:133:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/kexec.cc:44:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/antouank/.node-gyp/1.1.0/deps/v8/include/v8.h:878:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/kexec.cc:67:19: error: member access into incomplete type 'const v8::internal::Arguments'
    if ( 1 == args.Length() && args[0]->IsString() )
                  ^
/Users/antouank/.node-gyp/1.1.0/deps/v8/include/v8.h:133:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/kexec.cc:69:37: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        String::Utf8Value v8str(args[0]);
                                ~~~~^~
../src/kexec.cc:78:44: error: too few arguments to function call, expected 2, have 1
        Local<Number> num = Number::New(err);
                            ~~~~~~~~~~~    ^
/Users/antouank/.node-gyp/1.1.0/deps/v8/include/v8.h:2291:3: note: 'New' declared here
  static Local<Number> New(Isolate* isolate, double value);
  ^
../src/kexec.cc:79:22: error: no member named 'Close' in 'v8::HandleScope'
        return scope.Close(num/*Undefined()*/);
               ~~~~~ ^
../src/kexec.cc:83:19: error: member access into incomplete type 'const v8::internal::Arguments'
    if ( 2 == args.Length() && args[0]->IsString() && args[1]->IsArray() )
                  ^
/Users/antouank/.node-gyp/1.1.0/deps/v8/include/v8.h:133:7: note: forward declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/kexec.cc:85:37: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        String::Utf8Value v8str(args[0]);
                                ~~~~^~
../src/kexec.cc:89:59: error: type 'const v8::internal::Arguments' does not provide a subscript operator
        Local<Array> argv_handle = Local<Array>::Cast(args[1]);
                                                      ~~~~^~
../src/kexec.cc:101:66: error: too few arguments to function call, expected 2, have 1
            String::Utf8Value arg(argv_handle->Get(Integer::New(i))->ToString());
                                                   ~~~~~~~~~~~~  ^
/Users/antouank/.node-gyp/1.1.0/deps/v8/include/v8.h:2304:3: note: 'New' declared here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
../src/kexec.cc:118:44: error: too few arguments to function call, expected 2, have 1
        Local<Number> num = Number::New(err);
                            ~~~~~~~~~~~    ^
/Users/antouank/.node-gyp/1.1.0/deps/v8/include/v8.h:2291:3: note: 'New' declared here
  static Local<Number> New(Isolate* isolate, double value);
  ^
../src/kexec.cc:119:22: error: no member named 'Close' in 'v8::HandleScope'
        return scope.Close(num/*Undefined()*/);
               ~~~~~ ^
../src/kexec.cc:127:49: error: no member named 'New' in 'v8::String'
    ThrowException(Exception::TypeError(String::New("kexec: invalid arguments")));
                                        ~~~~~~~~^
../src/kexec.cc:128:18: error: no member named 'Close' in 'v8::HandleScope'
    return scope.Close(Undefined());
           ~~~~~ ^
../src/kexec.cc:128:24: error: no matching function for call to 'Undefined'
    return scope.Close(Undefined());
                       ^~~~~~~~~
/Users/antouank/.node-gyp/1.1.0/deps/v8/include/v8.h:323:28: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
  friend Handle<Primitive> Undefined(Isolate* isolate);
                           ^
../src/kexec.cc:134:9: error: no matching function for call to 'NODE_SET_METHOD'
        NODE_SET_METHOD(target, "kexec", kexec);
        ^~~~~~~~~~~~~~~
/Users/antouank/.node-gyp/1.1.0/src/node.h:218:25: note: expanded from macro 'NODE_SET_METHOD'
#define NODE_SET_METHOD node::NODE_SET_METHOD
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/antouank/.node-gyp/1.1.0/src/node.h:206:13: note: candidate function [with TypeName = v8::Handle<v8::Object>] not viable: no known conversion from
      'Handle<v8::Value> (const v8::internal::Arguments &)' to 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') for 3rd argument
inline void NODE_SET_METHOD(const TypeName& recv,
            ^
19 errors generated.
make: *** [Release/obj.target/kexec/src/kexec.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:100:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1040:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/antouank/_REPOS_/immutabix/node_modules/6to5/node_modules/kexec
gyp ERR! node -v v1.1.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm WARN optional dep failed, continuing kexec@1.0.0

> fsevents@0.3.5 install /Users/antouank/_REPOS_/immutabix/node_modules/6to5/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished
npm WARN prefer global 6to5@3.5.0 should be installed with -g
6to5@3.5.0 node_modules/6to5
├── fs-readdir-recursive@0.1.0
├── supports-color@1.2.0
├── roadrunner@1.0.4
├── globals@5.1.0
├── js-tokenizer@1.3.3
├── private@0.1.6
├── commander@2.6.0
├── estraverse@1.9.1
├── esutils@1.1.6
├── debug@2.1.1 (ms@0.6.2)
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── ast-types@0.6.10
├── output-file-sync@1.1.0 (xtend@4.0.0, mkdirp@0.5.0)
├── acorn-6to5@0.11.1-27
├── source-map@0.1.43 (amdefine@0.1.0)
├── source-map-support@0.2.9 (source-map@0.1.32)
├── detect-indent@3.0.0 (get-stdin@3.0.2, minimist@1.1.0, repeating@1.1.1)
├── core-js@0.4.10
├── regexpu@1.1.0 (regjsgen@0.2.0, regenerate@1.2.1, regjsparser@0.1.3, recast@0.9.17)
├── lodash@3.0.0
├── useragent@2.1.5 (lru-cache@2.2.4)
├── regenerator-6to5@0.8.9-8 (through@2.3.6, commoner@0.10.1)
└── chokidar@0.12.6 (async-each@0.1.6, readdirp@1.3.0, fsevents@0.3.5)
➜  immutabix git:(develop) ✗ node --version && npm --version && node -p process.versions
v1.1.0
2.4.1
{ http_parser: '2.3.0',
  node: '1.1.0',
  v8: '4.1.0.14',
  uv: '1.3.0',
  zlib: '1.2.8',
  ares: '1.10.0-DEV',
  modules: '43',
  openssl: '1.0.1k' }
➜  immutabix git:(develop) ✗
```

**Comment by sebmck** [comment]
See #691. It's an `optionalDependency` and 6to5 will work fine without it, signals just wont be propagated as they should be when using `6to5-node`.

**Comment by AntouanK** [comment]
I see. Thanks for letting us know.
