### ISSUE TITLE
Error: Cannot find module '6to5-runtime/helpers'

### ISSUE THREAD

**Issue by alawatthe** [6to5/6to5#724]
I am getting the following error, when I try to browserify a file generated by 6to5.

```
Error: Cannot find module '6to5-runtime/helpers' from '<path>'
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:51:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:159:43)
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:168:21
    at load (/usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:99:43)
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:105:22
    at /usr/local/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:99:15)
```
I am using 6to5 version 3.5.3, browserify version 8.1.3

The file, generated by 6to5, I am trying to browserify starts like this:
```js
"use strict";

var _to5Helpers = require("6to5-runtime/helpers");

var SomeModule = _to5Helpers.interopRequire(require("./SomeModule"));
```
Is this a (known) bug? Am I doing something wrong?

**Comment by AluisioASG** [comment]
Did you install the `6to5-runtime` package?  It's needed if you're using the `selfContained` transformer.

**Comment by sebmck** [comment]
You have the `selfContained` transformer enabled. You can either remove it from your config or `npm install --save 6to5-runtime`.

**Comment by alawatthe** [comment]
Installing the runtime fixed it. Thanks to both of you :-)
