### ISSUE TITLE
Cannot install 6to5

### ISSUE THREAD

**Issue by chrisabrams** [6to5/6to5#725]
When I try running `npm install 6to5` I get this error:

    gyp ERR! build error 
    gyp ERR! stack Error: You must run `node-gyp configure` first!

I've never seen this error message before. Is there some configuration requirement that was recently added?

The error is coming from the node module `kexec`.

`kexec` gives another error later on:

Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 534, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 527, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 512, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2138, in GenerateOutput
    os.path.dirname(makefile_path))
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/common.py", line 25, in __call__
    result = self.func(*args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/common.py", line 139, in RelativePath
    path = os.path.realpath(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 368, in realpath
    return abspath(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 356, in abspath
    cwd = os.getcwd()
OSError: [Errno 2] No such file or directory
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"

**Comment by sebmck** [comment]
You can safely ignore the kexec compile error, it's an optional dependency and not required. I'm probably going to remove it in a future version because it confuses so many people.

The requirements haven't changed so if npm reports that the installation was successful then everything will work fine.

**Comment by chrisabrams** [comment]
I'm actually unable to install it. It gets to:

    node_modules/6to5/node_modules/chokidar/node_modules/fsevents
    > node-gyp rebuild

and the process completely stops and exits.

**Comment by chrisabrams** [comment]
Just emailed you the entire log file.

**Comment by sebmck** [comment]
It looks like the result of a bad node install. You have some dev dependencies missing which will break the installation of a lot of stuff. It's possible that either you have a conflicting python installation or you don't have xcode.

**Comment by chrisabrams** [comment]
Upgrading node from `.0.10.29` to `0.10.33` resolved my issue.

**Comment by sebmck** [comment]
Good to hear!

**Comment by chrisabrams** [comment]
Thanks for the help :)
