### ISSUE TITLE
SyntaxError "Unterminated comment" (gulp-6to5)

### ISSUE THREAD

**Issue by stebru** [6to5/6to5#755]
I'm getting syntax error "Unterminated comment" (using gulp-6to5 v3.0.0). But the thing is, the file in question doesn't have any comments...

```shell
{ [SyntaxError: /Applications/XAMPP/xamppfiles/htdocs/uno/app/webroot/js/Fixtures/models/vessel_type.js: Unterminated comment (4:0)
  2  |   name: DS.attr('string')
  3  | }
> 4  | /*
     | ^]
  pos: 63,
  loc: { line: 4, column: 0 },
  raisedAt: 65,
  _6to5: true,
  name: 'SyntaxError',
  message: '/Applications/XAMPP/xamppfiles/htdocs/uno/app/webroot/js/Fixtures/models/vessel_type.js: Unterminated comment (4:0)\n  2  |   \u001b[37mname\u001b[39m\u001b[1m\u001b[37m:\u001b[39m\u001b[22m \u001b[37mDS\u001b[39m\u001b[1m\u001b[37m.\u001b[39m\u001b[22m\u001b[37mattr\u001b[39m\u001b[1m\u001b[34m(\u001b[39m\u001b[22m\u001b[31m\'string\'\u001b[39m\u001b[1m\u001b[34m)\u001b[39m\u001b[22m\n  3  | \u001b[32m}\u001b[39m\n> 4  | /*\n     | ^',
  stack: 'SyntaxError: /Applications/XAMPP/xamppfiles/htdocs/uno/app/webroot/js/Fixtures/models/vessel_type.js: Unterminated comment (4:0)\n  2  |   \u001b[37mname\u001b[39m\u001b[1m\u001b[37m:\u001b[39m\u001b[22m \u001b[37mDS\u001b[39m\u001b[1m\u001b[37m.\u001b[39m\u001b[22m\u001b[37mattr\u001b[39m\u001b[1m\u001b[34m(\u001b[39m\u001b[22m\u001b[31m\'string\'\u001b[39m\u001b[1m\u001b[34m)\u001b[39m\u001b[22m\n  3  | \u001b[32m}\u001b[39m\n> 4  | /*\n     | ^\n    at raise (/Applications/XAMPP/xamppfiles/htdocs/uno/node_modules/gulp-6to5/node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:343:15)\n    at skipBlockComment (/Applications/XAMPP/xamppfiles/htdocs/uno/node_modules/gulp-6to5/node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:736:21)\n    at skipSpace (/Applications/XAMPP/xamppfiles/htdocs/uno/node_modules/gulp-6to5/node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:793:11)\n    at finishToken (/Applications/XAMPP/xamppfiles/htdocs/uno/node_modules/gulp-6to5/node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:730:25)\n    at getTokenFromCode (/Applications/XAMPP/xamppfiles/htdocs/uno/node_modules/gulp-6to5/node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:972:32)\n    at readToken (/Applications/XAMPP/xamppfiles/htdocs/uno/node_modules/gulp-6to5/node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:1079:15)\n    at next (/Applications/XAMPP/xamppfiles/htdocs/uno/node_modules/gulp-6to5/node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:2105:5)\n    at eat (/Applications/XAMPP/xamppfiles/htdocs/uno/node_modules/gulp-6to5/node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:2211:7)\n    at parseExprList (/Applications/XAMPP/xamppfiles/htdocs/uno/node_modules/gulp-6to5/node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:3696:13)\n    at parseSubscripts (/Applications/XAMPP/xamppfiles/htdocs/uno/node_modules/gulp-6to5/node_modules/6to5-core/node_modules/acorn-6to5/acorn_csp.js:3133:24)',
  fileName: '/Applications/XAMPP/xamppfiles/htdocs/uno/app/webroot/js/Fixtures/models/vessel_type.js',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-6to5' }
```

vessel_type.js:
```javascript
App.VesselType = DS.Model.extend({
  name: DS.attr('string')
});

```

task:
```javascript
module.exports = function(gulp, plugins, paths) {

  return function() {

    var pkg = require('../../package.json');
    var js = require('../js');
    var to5 = require('gulp-6to5');

    Object.keys(js.paths).forEach(function(key) {
      gulp.src(js.paths[key], {
        base: 'app/webroot/js/'
      })
        .pipe(plugins.sourcemaps.init())
        .pipe(to5()).on('error', plugins.util.log)
        .pipe(plugins.concat(key + '.min.js'))
        .pipe(plugins.uglify()).on('error', plugins.util.log)
        .pipe(plugins.header(paths.banner, {
          pkg: pkg,
          util: plugins.util
        }))
        .pipe(plugins.sourcemaps.write('.', {
          includeContent: false,
          sourceRoot: '/app/webroot/js/'
        }))
        .pipe(gulp.dest(paths.destJs));
    });
  };
};
```

**Comment by stebru** [comment]
The file in question seems very random, though..

**Comment by sebmck** [comment]
Does it still happen if you remove all the other gulp plugins besides `gulp-6to5`?

**Comment by stebru** [comment]
Yes, I just tried this:

```javascript
module.exports = function(gulp, plugins, paths) {

  return function() {

    var pkg = require('../../package.json');
    var js = require('../js');
    var to5 = require('gulp-6to5');

    Object.keys(js.paths).forEach(function(key) {
      gulp.src(js.paths[key], {
        base: 'app/webroot/js/'
      })
        // .pipe(plugins.sourcemaps.init())
        .pipe(to5()).on('error', plugins.util.log)
        // .pipe(plugins.concat(key + '.min.js'))
        // .pipe(plugins.uglify()).on('error', plugins.util.log)
        // .pipe(plugins.header(paths.banner, {
        //   pkg: pkg,
        //   util: plugins.util
        // }))
        // .pipe(plugins.sourcemaps.write('.', {
        //   includeContent: false,
        //   sourceRoot: '/app/webroot/js/'
        // }))
        .pipe(gulp.dest(paths.destJs));
    });
  };
};
```

with same error output.

**Comment by sebmck** [comment]
Hm, can't seem to replicate this and not sure where to start. Any chance you could create a repo with code to reproduce? I'll take a look in the morning if possible.

**Comment by stebru** [comment]
That would be awesome! I'll try to set up a repo :)

**Comment by stebru** [comment]
Right, wasn't able to reproduce in new repo. After some debugging, seems to be totally unrelated to 6to5.  Was due to some unrelated tasks running in parallel which should have run in sequence. Don't understand the gulps error reporting, though... I'll read up on gulp ;)
